apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parasol-argocd-applications
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: parasol
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: parasol-argocd-applications
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: parasol
subjects:
  - kind: ServiceAccount
    name: parasol
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: parasol-argocd-applications
