{{- range .Values.catalogSources }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  sourceType: grpc
  image: {{ .image }}:{{ .tag }}
  displayName: {{ .displayName | quote }}
  publisher: {{ .publisher | quote }}
  {{- /* Override gRPC pod probes for large catalog images that need more time to load */}}
  {{- with .grpcPodConfig }}
  grpcPodConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
