kind: ConfigMap
metadata:
  name: parasol-insurance-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "0"
apiVersion: v1
data:
  playbook.yaml: |
    ---
    - name: Parasol Insurance webhook setup
      hosts: localhost
      tasks:
        - name: Wait for EventListener route
          kubernetes.core.k8s_info:
            api_version: route.openshift.io/v1
            kind: Route
            name: parasol-insurance-tag-listener
            namespace: {{ $.Values.build.namespace }}
          register: r_el_route
          retries: 60
          delay: 10
          until: r_el_route.resources | length > 0

        - name: Set EventListener URL
          ansible.builtin.set_fact:
            _el_url: "https://{{ "{{" }} r_el_route.resources[0].spec.host {{ "}}" }}"

        - name: Get parasol-insurance project ID
          ansible.builtin.uri:
            url: "https://{{ $.Values.gitlab.host }}/api/v4/projects/parasol%2Fparasol-insurance"
            method: GET
            headers:
              PRIVATE-TOKEN: "{{ "{{" }} lookup('env', 'GITLAB_TOKEN') {{ "}}" }}"
            validate_certs: false
          register: r_project
          retries: 30
          delay: 10
          until: r_project.status == 200

        - name: Check existing webhooks
          ansible.builtin.uri:
            url: "https://{{ $.Values.gitlab.host }}/api/v4/projects/{{ "{{" }} r_project.json.id {{ "}}" }}/hooks"
            method: GET
            headers:
              PRIVATE-TOKEN: "{{ "{{" }} lookup('env', 'GITLAB_TOKEN') {{ "}}" }}"
            validate_certs: false
          register: r_hooks

        - name: Create tag push webhook
          ansible.builtin.uri:
            url: "https://{{ $.Values.gitlab.host }}/api/v4/projects/{{ "{{" }} r_project.json.id {{ "}}" }}/hooks"
            method: POST
            headers:
              PRIVATE-TOKEN: "{{ "{{" }} lookup('env', 'GITLAB_TOKEN') {{ "}}" }}"
            body_format: json
            body:
              url: "{{ "{{" }} _el_url {{ "}}" }}"
              token: "{{ "{{" }} lookup('env', 'GITLAB_TOKEN') {{ "}}" }}"
              tag_push_events: true
              push_events: true
              enable_ssl_verification: false
            validate_certs: false
            status_code: 201
          when: r_hooks.json | selectattr('url', 'equalto', _el_url) | list | length == 0
