apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-token
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: gitlab-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secrets/gitlab/token
        property: value
