apiVersion: batch/v1
kind: Job
metadata:
  name: parasol-insurance-webhook
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 100
  template:
    spec:
      serviceAccountName: {{ include "parasol-insurance.name" . }}
      containers:
        - name: parasol-insurance-webhook
          command:
            - /bin/bash
            - '-c'
            - |
              set -x
              ansible-playbook -i localhost /scripts/playbook.yaml
          image: quay.io/agnosticd/ee-multicloud:latest
          env:
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-token
                  key: token
          volumeMounts:
            - mountPath: /scripts
              name: scripts
      restartPolicy: Never
      volumes:
        - name: scripts
          configMap:
            name: parasol-insurance-webhook
