---
apiVersion: v1
kind: Service
metadata:
  name: shipwright-build-controller-metrics
  namespace: openshift-builds
  labels:
    app.kubernetes.io/component: build-controller
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - name: metrics
      port: 8383
      targetPort: 8383
      protocol: TCP
  selector:
    name: shipwright-build
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shipwright-build-controller
  namespace: openshift-builds
  labels:
    app.kubernetes.io/component: build-controller
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
  namespaceSelector:
    matchNames:
      - openshift-builds
  selector:
    matchLabels:
      app.kubernetes.io/component: build-controller
