---
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  namespace: {{ .Values.istio.namespace }}
  values:
    meshConfig:
      discoverySelectors:
        - {{- .Values.istio.discoverySelector | toYaml | nindent 10 }}
