{{- range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name | replace "_" "-" }}
  {{- if $.Values.namespace }}
  namespace: {{ $.Values.namespace }}
  {{- end }}
  labels:
    strimzi.io/cluster: {{ include "kafka-broker.name" $ }}
    {{- include "kafka-broker.labels" $ | nindent 4 }}
  annotations:
    {{- include "kafka-broker.argocd-syncwave" $ | nindent 4 }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  partitions: {{ .partitions }}
  replicas: {{ $.Values.kafka.config.defaultReplicationFactor }}
  config:
    retention.ms: {{ .retention }}
    segment.bytes: 1073741824
  topicName: {{ .name }}
{{- end }}
