{{- if eq .Values.authentication.saslMechanism "SCRAM-SHA-512" -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "kafka-broker.name" . }}-user-secret
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-broker.argocd-syncwave" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ include "kafka-broker.name" . }}-user-secret
    creationPolicy: Owner
  data:
    - secretKey: clientSecret
      remoteRef:
        key: secrets/kafka/user-password
        property: value
{{- end }}
