apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: continue-llm-credentials
  namespace: {{ include "devspaces-instance.namespace" . }}
  annotations:
    {{- include "devspaces-instance.argocd-syncwave" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: continue-llm-credentials
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: che.eclipse.org
          app.kubernetes.io/component: workspaces-config
        annotations:
          controller.devfile.io/mount-as: env
      data:
        LLM_API_KEY: "{{ printf "{{ .api_key }}" }}"
        LLM_BASE_URL: "{{ printf "{{ .base_url }}" }}"
  data:
    - secretKey: api_key
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
    - secretKey: base_url
      remoteRef:
        key: secrets/litellm/credentials
        property: base_url
