{{- range $ns := .Values.namespaces }}
{{- range $user := $.Values.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $user }}-admin
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.clusterRole }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ $user }}
{{- end }}
{{- end }}
