apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "developer-hub-prereqs.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
