---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonardb
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
