---
apiVersion: v1
kind: Service
metadata:
  name: sonardb
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    name: sonardb
