{{- if .Values.sonarqube.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sonarqube
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: sonarqube
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.sonarqube.route.tlsTermination }}
  wildcardPolicy: None
{{- end }}
