---
apiVersion: v1
kind: Secret
metadata:
  name: sonardb
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-name: {{ .Values.postgresql.database }}
  database-user: {{ .Values.postgresql.username }}
  database-password: {{ .Values.postgresql.password }}
