---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.sonarqube.port }}
      targetPort: {{ .Values.sonarqube.port }}
  selector:
    name: sonarqube
