---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-data
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sonarqube.persistence.size }}
